
<!DOCTYPE html>
<html lang="en">


<?php


?>


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

        <title>CCC KARUNAGAPPALLY</title>


    <!-- Bootstrap core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="../assets/css/fontawesome.css">
    <link rel="stylesheet" href="../assets/css/home.css">
    <link rel="stylesheet" href="../assets/css/owl.css">

</head>


<style>


    body {
        background-image: url(../assets/images/notification.jpg);
    }

    .footer {

        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #000000;
        color: white;
        text-align: center;
    }


</style>

<body>


<!--header-->
<header class="main-header clearfix" role="header">
    <div class="logo">
        <a href=""><em>CCC</em> KARUNAGAPPALLY</a>
    </div>

</header>

<!-- ***** Main Banner Area Start ***** -->

<div class="container-fluid" >
    <div class="fixed-center"  ><br/><br/><br/><br/><br/><br/>
        <div class="container" >

            <section class="row justify-content-center" >
                <section class="col-10 col-sm-4 col-md-3" >

                    <form class="text-center border border-light p-3"  method="post" action="">

                        <p class="h4 mb-4" align="center"><font color="#FFFFFF"> Log in</font></p>

                        <div class="form-group">

                            <input type="text" name="user_login" class="form-control" id="username" aria-describedby="username" placeholder="Username">

                        </div>
                        <div class="form-group">

                            <input type="password" name="user_password" class="form-control" id="password" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-success btn-block" name="login">Login</button>

                    </form>

                </section>
            </section>
        </div>
    </div>
</div>

<footer>
    <div class="footer">
        <div class="row">
            <div class="col-md-12">
                <p><i class="fa fa-copyright"></i> Copyright 2021 CCC KARUNAGAPPALLY

                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="../assets/js/isotope.min.js"></script>
<script src="../assets/js/owl-carousel.js"></script>
<script src="../assets/js/lightbox.js"></script>
<script src="../assets/js/tabs.js"></script>
<script src="../assets/js/video.js"></script>
<script src="../assets/js/slick-slider.js"></script>
<script src="../assets/js/custom.js"></script>

</body>
</html>